### ISSUE TITLE
Sign Lobbyradar extension so it's not disabled in Firefox 43

### ISSUE THREAD

**Issue by foss-** [lobbyradar/lobbyradar#3]
Firefox 43 arrived a few days ago. Unsigned extension are now disabled by default. Lobbyradar is thus no longer usable in Firefox.

Since Lobbyradar is no longer supported by the german Öffentlich Rechtliche Zwangsabgabe, I hope you can find new sponsors. This is essential technology and should be further supported by core political institutions.

ZDF, shame on your corrupt leadership!

**Comment by yetzt** [comment]
sorry, the externsion is not part of this repository and, to my knowledge, not free software.

**Comment by foss-** [comment]
Thanks for responding after such a long time. That was very unexpected.

So the extension never was part of this repository? Do you know where it is located? Does that mean the extension was coded with public money under proprietary license?

Are there any plans to bring it back to life?

**Comment by yetzt** [comment]
sorry for taking such a long time, i just stumbled on this issue while doing maintainance on old code. 

the repository of the browser extenstion can be found here: https://github.com/wegewerk/lobbyradar-extension

also i stand corrected: the extension appears to be released under the MIT license.
